version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 290902
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    networks:
      - app-net

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-net

  consul:
    image: hashicorp/consul:1.16
    container_name: consul
    ports:
      - "8500:8500"
    command: agent -dev -client=0.0.0.0
    networks:
      - app-net

  auth-service:
    build: ./AuthService/AuthService
    image: whisperingpages/auth-service:latest
    container_name: auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/auth_db_flyway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 290902
    depends_on:
      - mysql
      - redis
      - consul
    ports:
      - "8086:8086"
    networks:
      - app-net

  cart-service:
    build: ./CartService/CartService
    image: whisperingpages/cart-service:latest
    container_name: cart-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cart_db_flyway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 290902
    depends_on:
      - mysql
      - redis
      - consul
    ports:
      - "8089:8089"
    networks:
      - app-net

  orders-service:
    build: ./OrderService/OrderService
    image: whisperingpages/orders-service:latest
    container_name: orders-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/orders_db_flyway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 290902
    depends_on:
      - mysql
      - redis
      - consul
    ports:
      - "8090:8090"
    networks:
      - app-net

  product-service:
    build: ./ProductService/ProductService
    image: whisperingpages/product-service:latest
    container_name: product-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/product_db_flyway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 290902
    depends_on:
      - mysql
      - consul
    ports:
      - "8088:8088"
    networks:
      - app-net

  user-service:
    build: ./UserService/UserService
    image: whisperingpages/user-service:latest
    container_name: user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/user_db_flyway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 290902
    depends_on:
      - mysql
      - consul
    ports:
      - "8083:8083"
    networks:
      - app-net

  gateway-service:
    build: ./Gateway/Gateway
    image: whisperingpages/gateway-service:latest
    container_name: gateway-service
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - auth-service
      - user-service
      - product-service
      - cart-service
      - orders-service
      - consul
      - redis
    ports:
      - "8085:8085"
    networks:
      - app-net

  book-client:
    build: ./Client/ClientBook
    image: whisperingpages/book-client:latest
    container_name: book-client
    ports:
      - "4200:80"
    depends_on:
      - gateway-service
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
