# ========== Stage 1: Build ==========
FROM maven:3.9.6-eclipse-temurin-17 AS builder
WORKDIR /app

COPY . .

RUN mvn clean package -DskipTests

# ========== Stage 2: Run ==========
FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar

# CartService chạy port 8089
EXPOSE 8089

ENTRYPOINT ["java", "-jar", "app.jar"]
