server:
  port: 8089

spring:
  application:
    name: cart-service

  datasource:
    url: jdbc:mysql://mysql:3306/cart_db_flyway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 290902
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  flyway:
    enabled: true          # nếu bạn có script trong resources/db/migration
    baseline-on-migrate: true
    locations: classpath:db/migration

  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}
      timeout: 10s
      client-type: lettuce

  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        enabled: true
        register: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
