server:
  port: 8085

spring:
  application:
    name: gateway-service

  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}
      timeout: 10s
      client-type: lettuce

#  redis:
#    host: ${SPRING_REDIS_HOST:redis}
#    port: ${SPRING_REDIS_PORT:6379}
#    timeout: 10s
#    client-type: lettuce

  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:consul}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 10s

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
        - id: reports-service
          uri: lb://product-service
          predicates:
            - Path=/api/reports/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/cart/**
        - id: orders-service
          uri: lb://orders-service
          predicates:
            - Path=/api/orders/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY

logging:
  level:
    org.springframework.data.redis: DEBUG
