server:
  port: 8086

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://mysql:3306/auth_db_flyway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 290902
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: ${SPRING_REDIS_PORT:6379}
    client-type: lettuce
    timeout: 5s

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 128659255641-t6q4akllndemks7bs2jcuaugur16p5kc.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=select_account
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:consul}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      discovery:
        enabled: true
        register: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.data.redis: DEBUG
