server:
  port: 8083

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://mysql:3306/user_db_flyway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 290902
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  flyway:
    enabled: false           # ❌ tắt nếu bạn chỉ dùng dump/init data
    baseline-on-migrate: true

  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        enabled: true
        register: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
